# backend/src/main/resources/application-oracle.yml
spring:
  datasource:
    url: ${DB_URL:jdbc:oracle:thin:@localhost:1521/FREEPDB1}
    username: ${DB_USER:system}
    password: ${DB_PASS:oracle}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
        jdbc.time_zone: UTC
  flyway:
    enabled: true
    locations: classpath:db/migration/oracle
